version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - KUBECONFIG=/var/.kube/configdd
    volumes:
      - C:/Users/nweis/.kube:/var/.kube
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
