{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" "re-api-key" (include "itl.common.fullname" .)) }}
{{- if not $existing }}
{{- $timestamp := now | date "20060102150405" }}
{{- $random := randAlphaNum 30 }}
{{- $raw := printf "%s:%s:%s" .Release.Name $timestamp $random }}
{{- $hash := sha256sum $raw }}
{{- $apiKey := printf "%s:%s" $raw $hash | b64enc }}

apiVersion: v1
kind: Secret
metadata:
  name: re-api-key
type: Opaque
data:
    api-key: {{ $apiKey | b64enc }}
{{- end }}