{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" "re-api-key" (include "itl.common.fullname" .)) }}
{{- if not $existing }}
{{- $apiKey := printf "%s:%d:%s" .Release.Name (now | date "20060102150405") (randAlphaNum 30) | b64enc }}

apiVersion: v1
kind: Secret
metadata:
    name: re-api-key
    labels:
        {{- include "itl.common.labels" . | nindent 4 }}
type: Opaque
data:
    api-key: {{ $apiKey | b64enc }}
{{- end }}