apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: {{ .Release.Namespace }}
data:
  oauth2-proxy.cfg: |-
    provider = "keycloak-oidc"
    oidc_issuer_url = "https://sts.itlusions.com/realms/itlusions"
    upstreams = [ "http://{{ include "itl.common.fullname" . }}:{{ .Values.service.port }}" ]
    pass_basic_auth = false
    pass_access_token = true