apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: describe-crds-cluster
rules:
  # Permissions for listing CRDs
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]

  # Permissions for accessing specific CRD items
  - apiGroups: ["*"]  # Allow access to all API groups
    resources: ["*"]  # Allow access to all custom resources
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-describe-crds-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "itl.common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: describe-crds-cluster
  apiGroup: rbac.authorization.k8s.io