apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-ingresses-and-services-cluster
rules:
  # Permissions for ingresses
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "get"]
  # Permissions for services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-list-ingresses-and-services-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "itl.common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: list-ingresses-and-services-cluster
  apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: get-namespaces-cluster
  rules:
    # Permissions for namespaces
    - apiGroups: [""]
      resources: ["namespaces"]
      verbs: ["get"]

  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: bind-get-namespaces-cluster
  subjects:
    - kind: ServiceAccount
      name: {{ include "itl.common.serviceAccountName" . }}
      namespace: {{ .Release.Namespace }}
  roleRef:
    kind: ClusterRole
    name: get-namespaces-cluster
    apiGroup: rbac.authorization.k8s.io