apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: describe-resources-cluster
rules:
  # Permissions for pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  # Permissions for services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get"]
  # Permissions for deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-describe-resources-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "itl.common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: describe-resources-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stream-events-cluster
rules:
  # Permissions for events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-stream-events-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "itl.common.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: stream-events-cluster
  apiGroup: rbac.authorization.k8s.io